# -------------------- LOAD ENV --------------------
from dotenv import load_dotenv
import os

# Load .env file (contains GROQ_API_KEY)
load_dotenv()

# -------------------- IMPORTS --------------------
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field


# -------------------- DEFINE PYDANTIC MODEL --------------------
# This defines structure of output we expect from LLM
class Movie(BaseModel):
    title: str = Field(description="Title of the movie")
    director: str = Field(description="Director of the movie")
    year: int = Field(description="Release year")
    description: str = Field(description="Short summary of the movie")


# -------------------- INITIALIZE MODEL --------------------
model = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.7,
    groq_api_key=os.getenv("GROQ_API_KEY")
)


# -------------------- CREATE PYDANTIC PARSER --------------------
parser = PydanticOutputParser(pydantic_object=Movie)


# -------------------- PROMPT TEMPLATE --------------------
template = PromptTemplate(
    input_variables=["movie"],
    
    # format instructions auto generated by parser
    partial_variables={
        "format_instructions": parser.get_format_instructions()
    },

    template="""
You are a helpful assistant.

Give movie details in JSON format.

Movie: {movie}

{format_instructions}
"""
)


# -------------------- CREATE CHAIN --------------------
# prompt → model → parser
chain = template | model | parser


# -------------------- INVOKE --------------------
response = chain.invoke({
    "movie": "Inception"
})


# -------------------- OUTPUT --------------------
print("\nPydantic Object:\n")
print(response)

print("\nAccess fields individually:\n")
print("Title:", response.title)
print("Director:", response.director)
print("Year:", response.year)

print("\nJSON format:\n")
print(response.model_dump_json(indent=2))