# This program gives some information to the AI, asks a question,
# and the AI answers only from that information.

# Load environment variables (like API keys) from .env file
from dotenv import load_dotenv
import os

# Import Groq chat model and prompt template classes from LangChain
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate

load_dotenv()


# Initialize the Groq chat model
model = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.0,
    groq_api_key=os.getenv("GROQ_API_KEY")
)

# Define a reusable prompt template with placeholders {context} and {question}
template = PromptTemplate.from_template(
    """You are a helpful assistant that answers questions based on the provided context.
If you can't find the answer in the context, say 'I don't know'.
Context: {context}
Question: {question}
Answer:"""
)

# Provide actual context and question to fill the template
user_input = {
    "context": "The capital of India is New Delhi. It is the seat of the government of India and is known for its rich history and cultural heritage.",
    "question": "What is the capital of India?"
}

# A chain is like a conveyor belt for tasks.
# It connects different steps so that the output of one step
# becomes the input of the next step automatically.
chain = template | model  

# Send the filled prompt to the model and get the response
response = chain.invoke(user_input)

# Print a separator for clarity
print("--------------------------------")

# Print the actual text generated by the model
print(response.content)