# -------------------------------
# Step 1: Import libraries
# -------------------------------
from dotenv import load_dotenv
import os
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage

# Load environment variables (like API keys)
load_dotenv()


# -------------------------------
# Step 2: Initialize the chat model
# -------------------------------
# model="llama-3.3-70b-versatile" → Groq’s general-purpose LLM
# temperature=0.0 → deterministic answers (no randomness)
model = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.0,
    groq_api_key=os.getenv("GROQ_API_KEY")
)


# -------------------------------
# Step 3: Create system message
# -------------------------------
# SystemMessage sets rules or behavior for the AI assistant
# Here, we instruct it to give simple, clear, factual answers for children aged 8–12
sys_prompt = SystemMessage(
    content="""
You are a helpful assistant that answers questions about current events and general knowledge for children aged 8–12.
Ensure your answers are simple, clear, and age-appropriate.
If you don't know, say 'I don't know' instead of making up an answer.
Always provide accurate and factual information.
"""
)


# -------------------------------
# Step 4: Create human message
# -------------------------------
# HumanMessage contains the actual question from the user
human_prompt = HumanMessage(content="What is the capital of France?")


# -------------------------------
# Step 5: Send prompts to the model
# -------------------------------
# invoke() takes a list of messages: system instructions + user question
# The model returns a response object
response = model.invoke([sys_prompt, human_prompt])


# -------------------------------
# Step 6: Print the AI's answer
# -------------------------------
# response.content contains the text generated by the model
print(response.content)
 

